---
- name: Track git repos
  ansible.builtin.include_tasks: track_dev_git_repo.yml
  loop: "{{ ic_dev_gits }}"

- name: Track git repos
  ansible.builtin.include_tasks: track_git_repo.yml
  loop: "{{ ic_gits }}"
  when: |
    item|regex_replace('^(?:.*/(.+)|.*/([^/]+))$', '\\1') is not in
    ( ic_dev_gits |
    map('regex_replace', '^(?:.*/(.+)|.*/([^/]+))$', '\\1') | list)

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Track RPMs
  ansible.builtin.include_tasks: track_rpm.yml
  loop: "{{ ic_rpms }}"
  when:
    - item is not in
      ( (ic_gits + ic_dev_gits) |
        map('regex_replace', '^(?:.*/(.+)|.*/([^/]+))$', '\\1') |
        map('regex_replace', 'python', 'python3') | list)
    - item in ansible_facts.packages
...
