---
- name: "Install required packages"
  ansible.builtin.yum:
    name: "{{ default_pkg_list }}"
    state: present
    update_cache: true
    disable_gpg_check: true
  become: true
  tags: packages

- name: "Install specific packages for SNO virtual"
  ansible.builtin.yum:
    name: "{{ snovm_pkg_list }}"
    state: present
    disable_gpg_check: true
  become: true
  when:
    - (sno_install_type is undefined) or (sno_install_type == "virtual")
  tags: packages
...
