---
- name: "Enable and restart Services"
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
    enabled: true
  become: true
  with_items:
    - libvirtd
  when:
    - sno_install_type | default("virtual") == "virtual"
  tags: services

- name: "Enable Services (iptables)"
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
    enabled: true
  become: true
  with_items:
    - "{{ firewall }}"
  when: firewall == "iptables"
  tags: services

- name: "Enable Services (firewalld)"
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  become: true
  with_items:
    - "{{ firewall }}"
  when: firewall != "iptables"
  tags: services
...
