---
- name: Does network exist
  community.libvirt.virt_net:
    name: "{{ network['name'] }}"
    command: status
  register: network_exists
  become: true
  ignore_errors: true
  tags:
    - cleanup

- name: Stop SNO network
  community.libvirt.virt_net:
    command: destroy
    name: "{{ network['name'] }}"
  become: true
  when:
    - not network_exists.failed
  tags:
    - cleanup

- name: Undefine SNO network
  community.libvirt.virt_net:
    command: undefine
    name: "{{ network['name'] }}"
  become: true
  when:
    - not network_exists.failed
  tags:
    - cleanup
...
