---
- name: Clean up NetworkManager Dnsmasq entries (RedHat)
  when:
    - ansible_facts['distribution'] == "RedHat"
  tags:
    - cleanup
  block:
    - name: Undefine DNS entries to be redirected in SNO
      ansible.builtin.file:
        path: /etc/NetworkManager/dnsmasq.d/{{ network['name'] }}.conf
        state: absent
      become: true
      loop: "{{ networks }}"
      loop_control:
        loop_var: network

    - name: Verify if there are more config files in NM dnsmasq.d
      ansible.builtin.shell: >
        ls /etc/NetworkManager/dnsmasq.d/ | wc -l
      register: dnsmasqconf

    - name: Remove dnsmasq from the DNS configuration of NetworkManager
      ansible.builtin.file:
        path: /etc/NetworkManager/conf.d/dnsmasq.conf
        state: absent
      become: true
      when: dnsmasqconf.stdout == "0"

    - name: Reload Network Manager
      ansible.builtin.service:
        name: NetworkManager
        state: reloaded
      become: true

- name: Clean up /etc/hosts entries (Fedora)
  ansible.builtin.lineinfile:
    path: /etc/hosts
    state: absent
    regex: "^{{ sno_extnet_ip }} api.{{ cluster }}.{{ domain }}"
  become: true
  when:
    - ansible_facts['distribution'] == "Fedora"
  tags:
    - cleanup
...
