---
- name: Remove Kubeconfig from Ansible User .bashrc
  ansible.builtin.lineinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    state: absent
    regex: "^export KUBECONFIG={{ dir }}/auth/kubeconfig"
  tags:
    - cleanup
