---
- name: Define, Start, Autostart Storage Pool
  become: true
  tags:
    - storagepool
  block:
    - name: Define Storage Pool for default
      community.libvirt.virt_pool:
        command: define
        name: "{{ vm_pool_name }}"
        xml: '{{ lookup("template", "dir.xml.j2") }}'

    - name: Start Storage Pool for default
      community.libvirt.virt_pool:
        state: active
        name: "{{ vm_pool_name }}"

    - name: Autostart Storage Pool for default
      community.libvirt.virt_pool:
        autostart: true
        name: "{{ vm_pool_name }}"
