---
- name: Define, Start, Libvirt Network
  become: true
  tags: virtnetwork
  block:
    - name: Define network
      community.libvirt.virt_net:
        command: define
        name: "{{ network['name'] }}"
        xml: '{{ lookup("template", "network.xml.j2") }}'

    - name: Start network
      community.libvirt.virt_net:
        state: active
        name: "{{ network['name'] }}"

    - name: Autostart network
      community.libvirt.virt_net:
        autostart: true
        name: "{{ network['name'] }}"
