---
- name: Add DNS /etc/hosts entries (Fedora)
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ sno_extnet_ip }} api.{{ cluster }}.{{ domain }}"
  become: true
  tags:
    - dnsredirect
