---
- name: "Create tmp tool directory"
  ansible.builtin.tempfile:
    state: directory
  register: cv_tool_dir

- name: "Set GH version"
  ansible.builtin.set_fact:
    gh_version: "{{ gh_version | default('2.12.1') }}"

- name: "Unarchive GH release tarball"
  ansible.builtin.unarchive:
    src: "https://github.com/cli/cli/releases/download/v{{ gh_version }}/gh_{{ gh_version }}_linux_amd64.tar.gz"
    dest: "{{ cv_tool_dir.path }}"
    remote_src: true
    extra_opts:
      - --strip-components=2

- name: "Set tools path"
  ansible.builtin.set_fact:
    gh_tool_path: "{{ cv_tool_dir.path }}/gh"
...
