---
- name: Print JSON draft for the project to be created
  vars:
    template_filename: "templates/create_project_{{ product_type }}.json.j2"
  ansible.builtin.debug:
    msg: "{{ lookup('template', template_filename) }}"

- name: Create certification project
  vars:
    pyxis_apikey: "{{ lookup('file', pyxis_apikey_path) }}"
    # TODO: check if templates could be merged or it's better as it is
    template_filename: "templates/create_project_{{ product_type }}.json.j2"
  ansible.builtin.uri:
    url: "{{ catalog_url }}/projects/certification"
    method: POST
    headers:
      X-API-KEY: "{{ pyxis_apikey }}"
    body_format: json
    body: "{{ lookup('template', template_filename) }}"
    status_code: 201
    timeout: 120
  register: cert_project_output

- name: Set project ID to reuse it later
  ansible.builtin.set_fact:
    cert_project_id: "{{ cert_project_output.json | json_query('_id') }}"  # noqa: jinja[invalid]
  when: not cert_project_output.failed

- name: Print the URL of created certification project
  ansible.builtin.debug:
    msg: |
      Certification project was created and could be checked here:
      {{ connect_url }}/{{ cert_project_id }}/overview
  when: not cert_project_output.failed
...
