---
- name: Validate cert_settings required to update the project
  ansible.builtin.include_tasks: validate_cert_settings.yml

- name: Print JSON draft for the project to be updated
  vars:
    # TODO: check if update project template differs between the product types
    template_filename: "templates/update_project_{{ product_type }}_setting.json.j2"
  ansible.builtin.debug:
    msg: "{{ lookup('template', template_filename) }}"

- name: Update certification project Settings
  vars:
    pyxis_apikey: "{{ lookup('file', pyxis_apikey_path) }}"
    # TODO: check if update project template differs between the product types
    template_filename: "templates/update_project_{{ product_type }}_setting.json.j2"
  ansible.builtin.uri:
    url: "{{ catalog_url }}/projects/certification/id/{{ cert_project_id }}"
    method: PATCH
    headers:
      X-API-KEY: "{{ pyxis_apikey }}"
    body_format: json
    body: "{{ lookup('template', template_filename) }}"
    status_code: 200
    timeout: 120
...
