---
# vars file for node_prep
el8_packages:
  - "{{ firewall }}"
  - ipmitool
  - jq
  - libsemanage-python3
  - libvirt
  - NetworkManager-libnm
  - nm-connection-editor
  - policycoreutils-python3
  - python3-devel
  - python3-libvirt
  - python3-lxml
  - python3-pyghmi
  - python3-yaml
  - qemu-kvm
  - tar

el9_packages:
  - "{{ firewall }}"
  - ipmitool
  - jq
  - libvirt
  - NetworkManager-libnm
  - nm-connection-editor
  - python3-devel
  - python3-libsemanage
  - python3-libvirt
  - python3-lxml
  - python3-policycoreutils
  - python3-pyghmi
  - python3-pyyaml
  - qemu-kvm
  - tar

package_list: "{{ (ansible_distribution_major_version == '9') | ternary(el9_packages, el8_packages) }}"

cache_package_list:
  - podman

qtype: "{{ ((ipv6_enabled|bool and (ipv4_baremetal|bool or dualstack_baremetal)) or (not ipv6_enabled|bool)) | ternary('qtype=A', 'qtype=AAAA') }}"


# Temporary state variables for disconnected registry
drm_set: false
dra_set: false
registry_host_exists: false

roothint_list:
  - deviceName
  - hctl
  - model
  - vendor
  - serialNumber
  - minSizeGigabytes
  - wwn
  - wwnWithExtension
  - wwnVendorExtension
  - rotational
  - ''
