---
- name: Handle the situation when cert project already exists
  ansible.builtin.include_role:
    name: create_certification_project
    tasks_from: check_if_container_project_exists
  when: check_for_existing_projects | bool

- name: Create Openshift-cnf project
  ansible.builtin.include_role:
    name: create_certification_project
    tasks_from: create_project
  when: cnf.create_cnf_project | default(false) | bool

- name: Set Openshift-cnf project to store new projects for later merging with existing IDs
  ansible.builtin.set_fact:
    new_openshift_cnf_projects: "{{ new_openshift_cnf_projects | default([]) + [cert_project_id] }}"
  when: cert_project_id is defined
...
