---
- name: "Set local_image_path"
  ansible.builtin.set_fact:
    local_image_path: "{{ libvirt_image_path | expanduser }}"

- name: "Ensure local_image_path directory exists"
  ansible.builtin.file:
    path: "{{ local_image_path }}"
    state: directory
    mode: "0755"
  become: "{{ libvirt_become }}"

- name: "Set image_src_basename"
  ansible.builtin.set_fact:
    image_src_basename: "{{ host['image_src'] | basename }}"

- name: "Register local_image_src absolute path"
  ansible.builtin.set_fact:
    local_image_src: "{{ local_image_path }}/{{ image_src_basename }}"


- name: "Does a local copy of image_src exist?"
  ansible.builtin.stat:
    path: "{{ local_image_src }}"
  register: lis

- name: "Download image_src"
  ansible.builtin.get_url:
    url: "{{ host['image_src'] }}"
    dest: "{{ local_image_src }}"
    mode: "0750"
  become: "{{ libvirt_become }}"
  when: not (lis.stat.exists | bool)

- name: "Determine image_src mime_type"
  # identify file type
  ansible.builtin.stat:
    path: "{{ local_image_src }}"
    mime: true
  become: "{{ libvirt_become }}"
  register: lismt

- name: "Set image_src for uncompressed files"
  ansible.builtin.set_fact:
    img_src: "{{ local_image_src }}"
  when: lismt.stat.mimetype == "application/octet-stream"

- name: "Set image_src basename to remove .xz extension"
  ansible.builtin.set_fact:
    img_src_basename: "{{ host['image_src'].split('.xz')[0] | basename }}"
  when: lismt.stat.mimetype == "application/x-xz"

- name: "Set img_src for xz compressed files"
  ansible.builtin.set_fact:
    img_src: "{{ local_image_path }}{{ img_src_basename }}"
  when: lismt.stat.mimetype == "application/x-xz"

- name: "Get img_src_basename extension"
  ansible.builtin.set_fact:
    img_src_ext: "{{ image_src_basename.split('.')[-1] }}"
  when: lismt.stat.mimetype != "application/x-xz"

- name: "Get img_src_basename extension"
  ansible.builtin.set_fact:
    img_src_ext: "{{ image_src_basename.split('.')[-2] }}"
  when: lismt.stat.mimetype == "application/x-xz"

- name: "Does img_src exist at local_image_path?"
  ansible.builtin.stat:
    path: "{{ img_src }}"
  become: "{{ libvirt_become }}"
  register: ismt
  when: lismt.stat.mimetype == "application/x-xz"

- name: "Uncompress xz local_image_src"
  ansible.builtin.command: "xz -d --keep --force {{ local_image_src }}"
  become: "{{ libvirt_become }}"
  when: lismt.stat.mimetype == "application/x-xz" and not (ismt.stat.exists | bool)

- name: "Copy img_src to match node name"
  ansible.builtin.command: "cp --sparse=always {{ img_src }} {{ local_image_path }}/{{ host['name'] }}.qcow2"
  become: "{{ libvirt_become }}"
...
