---
- name: Cleanup openshift dnsmasq settings
  ansible.builtin.file:
    path: /etc/NetworkManager/dnsmasq.d/openshift.conf
    state: absent
  become: "{{ libvirt_become }}"

- name: Restart NetworkManager
  ansible.builtin.service:
    name: NetworkManager
    state: restarted
  become: "{{ libvirt_become }}"
