---
- name: "Wait for VM to shut down"
  community.libvirt.virt:
    name: "{{ host['name'] }}"
    command: status
  register: vmstatus
  until: vmstatus.status == 'shutdown'
  retries: 150
  delay: 10
  when: ool_node_not_exists

- name: "Remove cdrom (cloud-init)"
  ansible.builtin.command: virsh change-media {{ host['name'] }} hda --eject --config
  become: "{{ libvirt_become }}"
  when: ool_node_not_exists

- name: Sync memory data to disk
  ansible.builtin.command: sync

- name: "Start VM again"
  community.libvirt.virt:
    name: "{{ host['name'] }}"
    state: "running"
  when: ool_node_not_exists
...
