---
- name: "Does node exist"
  community.libvirt.virt:
    name: "{{ host['name'] }}"
    command: status
  ignore_errors: true
  register: node_exists

- name: "Destroy node"
  community.libvirt.virt:
    name: "{{ host['name'] }}"
    command: destroy
  when: node_exists['status'] is defined and node_exists['status'] == 'running'

- name: "Undefine node"
  become: true
  ansible.builtin.command:
    # community.libvirt.virt undefine can't specify --nvram
    cmd: "virsh undefine --remove-all-storage --nvram {{ host['name'] }}"
  when: not node_exists.failed
