---
- name: "Does node exist"
  community.libvirt.virt_net:
    name: "{{ network['name'] }}"
    command: status
  ignore_errors: true
  register: node_exists

- name: "Destroy network"
  community.libvirt.virt_net:
    name: "{{ network['name'] }}"
    command: destroy
  when: not node_exists.failed

- name: "Undefine network"
  community.libvirt.virt_net:
    name: "{{ network['name'] }}"
    command: undefine
  when: not node_exists.failed
