---
- name: "Reset ssh connection to allow user changes to affect"
  ansible.builtin.meta: reset_connection

- name: Enable EPEL
  become: true
  ansible.builtin.package:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
  when: ansible_distribution_major_version == '7'

- name: Install packages required for libvirt
  become: true
  vars:
    _ool_python_packages_prefix: "{{ (ansible_python.version.major == 3) | ternary('python3', 'python') }}"
  ansible.builtin.package:
    name:
      - libvirt-daemon-kvm
      - git
      - genisoimage
      - libvirt
      - libvirt-daemon-kvm
      - virt-install
      - langpacks-en
      - glibc-all-langpacks
      - "libvirt-{{ _ool_python_packages_prefix }}"
      - "{{ _ool_python_packages_prefix }}-netaddr"
      - "{{ _ool_python_packages_prefix }}-lxml"
      - "python{{ ansible_python.version.major }}-pip"
      - "{{ _ool_python_packages_prefix }}-virtualenv"

- name: Get processor family
  ansible.builtin.set_fact:
    ool_proc_family: >-
      {{ ('AMD' in (ansible_processor | join)) | ternary('amd', 'intel') }}

- name: Check on nested KVM status
  ansible.builtin.set_fact:
    ool_nested_kvm: "{{ lookup('file', '/sys/module/kvm_' + ool_proc_family + '/parameters/nested') }}"

- name: Enable nested Virt
  become: true
  ansible.builtin.copy:
    content: |
      options kvm-{{ ool_proc_family }} nested=1
      options kvm-{{ ool_proc_family }} enable_shadow_vmcs=1
      options kvm-{{ ool_proc_family }} enable_apicv=1
      options kvm-{{ ool_proc_family }} ept=1
    dest: /etc/modprobe.d/kvm_nested.conf
    mode: "0644"
  when: ool_nested_kvm != 'Y'

- name: Reload KVM module
  become: true
  failed_when:
    - _ool_result.rc is defined
    - _ool_result.stderr is not ansible.builtin.regex('^.*Module kvm_(amd|intel) is in use.*$')
  register: _ool_result
  loop:
    - absent
    - present
  community.general.modprobe:
    name: "kvm_{{ ool_proc_family }}"
    state: "{{ item }}"
  when: ool_nested_kvm != 'Y'

- name: Enable and Start libvirtd
  become: true
  ansible.builtin.service:
    name: libvirtd
    enabled: true
    state: started

- name: Create the consoles directory
  become: true
  ansible.builtin.file:
    path: /var/lib/libvirt/consoles
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Set SELinux context under the consoles directory
  ansible.builtin.sefcontext:
    target: '/var/lib/libvirt/consoles(/.*)?'
    setype: svirt_home_t
  become: true

- name: Restore the contexts under the consoles directory
  ansible.builtin.command: /usr/sbin/restorecon -irv /var/lib/libvirt/consoles
  become: true

- name: "Add user to libvirt, kvm, and qemu groups"
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    append: true
    groups:
      - libvirt
      - qemu
      - kvm
