---
- name: "Reset ssh connection to allow user changes to affect"
  ansible.builtin.meta: reset_connection

- name: Enable EPEL
  become: true
  ansible.builtin.package:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
  when: ansible_distribution_major_version == '7'

- name: Install packages required for libvirt
  become: true
  ansible.builtin.package:
    name:
      - libvirt-daemon-kvm
      - git
      - genisoimage
      - libvirt
      - libvirt-daemon-kvm
      - virt-install
      - langpacks-en
      - glibc-all-langpacks
      - "libvirt-python{% if ansible_python.version.major == 3 %}3{% endif %}"
      - "python{% if ansible_python.version.major == 3 %}3{% endif %}-netaddr"
      - "python{% if ansible_python.version.major == 3 %}3{% endif %}-lxml"
      - "python{{ ansible_python.version.major }}-pip"
      - "python{% if ansible_python.version.major == 3 %}3{% endif %}-virtualenv"

- name: Get processor family
  ansible.builtin.set_fact:
    proc_family: "{{ ('AMD' in (ansible_processor | join)) | ternary('amd', 'intel') }}"

- name: Check on nested KVM status
  ansible.builtin.command: |
    cat /sys/module/kvm_{{ proc_family }}/parameters/nested
  ignore_errors: true
  register: nested_kvm

- name: Enable nested Virt
  become: true
  ansible.builtin.copy:
    content: |
      options kvm-{{ proc_family }} nested=1
      options kvm-{{ proc_family }} enable_shadow_vmcs=1
      options kvm-{{ proc_family }} enable_apicv=1
      options kvm-{{ proc_family }} ept=1
    dest: /etc/modprobe.d/kvm_nested.conf
    mode: "0644"
  when: nested_kvm.stdout != 'Y'

- name: Reload KVM module
  become: true
  loop:
    - absent
    - present
  community.general.modprobe:
    name: kvm_{{ proc_family }
    state: "{{ item }}"
  when: nested_kvm.stdout != 'Y'

- name: Enable and Start libvirtd
  become: true
  ansible.builtin.service:
    name: libvirtd
    enabled: true
    state: started

- name: Create the consoles directory
  become: true
  ansible.builtin.file:
    path: /var/lib/libvirt/consoles
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Set SELinux context under the consoles directory
  ansible.builtin.sefcontext:
    target: '/var/lib/libvirt/consoles(/.*)?'
    setype: svirt_home_t
  become: true

- name: Restore the contexts under the consoles directory
  ansible.builtin.command: /usr/sbin/restorecon -irv /var/lib/libvirt/consoles
  become: true

- name: "Add user to libvirt, kvm, and qemu groups"
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    append: true
    groups:
      - libvirt
      - qemu
      - kvm
