---
- name: "Set_ssh_key_name"
  ansible.builtin.set_fact:
    ssh_key_path: "{{ default_ssh_key_path | default('~/.ssh') | expanduser }}/{{ ssh_key }}"
  delegate_to: localhost

- name: "Does ssh key already exists ?"
  ansible.builtin.stat:
    path: "{{ ssh_key_path }}"
  register: ssh_key_stat_local
  delegate_to: localhost

- name: "Generate ssh keys when they don't exist"
  ansible.builtin.shell: |
    ssh-keygen -t rsa -f {{ ssh_key_path }} -N ''
    cat {{ ssh_key_path }}.pub >> ~/.ssh/authorized_keys
  args:
    creates: "{{ ssh_key_path }}"
  when: not (ssh_key_stat_local.stat.exists | bool)
  delegate_to: localhost

- name: "Ensure correct permissions on ~/.ssh/authorized_keys"
  ansible.builtin.file:
    path: "{{ '~' | expanduser }}/.ssh/authorized_keys"
    mode: "0644"
  delegate_to: localhost

- name: "Cat out contents of public key"
  ansible.builtin.slurp:
    src: "{{ ssh_key_path }}.pub"
  register: pubkey
  delegate_to: localhost
