---
- name: Handle package install
  ansible.builtin.include_tasks: packages.yml
- name: Handle configuration
  ansible.builtin.include_tasks: config.yml
- name: Handle systemd service
  ansible.builtin.include_tasks: service.yml
...
