---
- name: Deprecation message
  ansible.builtin.fail:  # noqa
    msg: "[DEPRECATED] This module has been deprecated in favor of k8s_best_practices_certsuite and will be removed in a future release"
  failed_when: false

- name: Run tnf stages
  block:
    - name: Execute cnf_cert pre-run stage
      ansible.builtin.include_tasks: pre-run.yml

    - name: Execute cnf_cert tests stage
      ansible.builtin.include_tasks: tests.yml

  always:
    - name: Execute cnf_cert teardown stage
      ansible.builtin.include_tasks: teardown.yml
...
