---
# global Preflight timeout = 180 seconds
- name: "Retrieve logs for operator {{ operator.name }}"
  vars:
    attempts:
      - one
      - two
      - three
  ansible.builtin.include_tasks: test_all_logs.yml
  loop: "{{ attempts }}"
...
