---
- name: Retrieve operator logs (global Preflight timeout = 180 seconds)
  vars:
    attempts:
      - one
      - two
      - three
  ansible.builtin.include_tasks: test_all_logs.yml
  loop: "{{ attempts }}"
...
