---
- name: Install junitparser needed to parse the tests
  ansible.builtin.pip:
    name:
      - junitparser
  become: true

- name: Loop over mandatory test results
  ansible.builtin.include_tasks: read_junit_files.yml
  loop: "{{ tests_to_verify }}"
  loop_control:
    loop_var: t
...
