---
# TODO: For nightlies we could sign the artifacts with --signing-key
- name: "Check if the release artifacts are in the cache"
  ansible.builtin.stat:
    path: "{{ mor_cache_dir }}/{{ mor_version }}/release.txt"
    get_checksum: false
  register: target
  when:
    - not mor_force

- name: "Extract artifacts from release image"
  ansible.builtin.command:
    cmd: >
      {{ mor_oc }} adm release extract
      --registry-config {{ mor_auths_file }}
      --tools
      --from {{ mor_pull_url }}
      --to "{{ mor_cache_dir }}/{{ mor_version }}"
  register: result
  retries: 3
  delay: 10
  until: result is not failed
  when:
    - mor_force or not target.stat.exists

- name: "Figure out status of SELinux"
  ansible.builtin.command: /usr/sbin/selinuxenabled
  ignore_errors: true
  register: selinux_status

- name: "Apply SELinux container file context to extracted files"
  ansible.builtin.sefcontext:
    target: "{{ mor_cache_dir }}/{{ mor_version }}"
    setype: container_file_t
  become: true
  when: selinux_status.rc == 0
...
