---
- name: "OCP release mirror"
  block:
    - name: "Check if the release image is pullable from the local registry"
      ansible.builtin.command: >
        skopeo inspect
        --no-tags
        --authfile {{ mor_auths_file }}
        docker://{{ mor_registry_url }}/{{ mor_registry_path }}:{{ mor_version }}

    - name: "Check for cached Image Source file"
      ansible.builtin.stat:
        path: "{{ mor_cache_dir }}/{{ mor_version }}/imagesource.yaml"
        get_checksum: false
      register: target

    - name: "Force mirroring if image source does not exist"
      ansible.builtin.fail:
        msg: "Cached image contents does not exits, forcing mirroring"
      when: not target.stat.exists

    - name: "Force mirroring is enabled"
      ansible.builtin.fail:
        msg: "Forcing the release mirroring"
      when:
        - mor_force | bool

  rescue:
    - name: "Mirror release images to local registry"
      ansible.builtin.command: >-
        {{ mor_cache_dir }}/{{ mor_version }}/oc adm release mirror
        --registry-config={{ mor_auths_file }}
        --from={{ ocp_release_data['container_image'] | quote }}
        --to-release-image={{ mor_registry_url }}/{{ mor_registry_path }}:{{ mor_version }}
        --to={{ mor_registry_url }}/{{ mor_registry_path }}
        {{ (mor_version is version("4.14", ">=") and mor_is_type | lower == "idms") | ternary("--print-mirror-instructions=idms", "") }}
      retries: 3
      delay: 10
      register: _mor_result
      until: _mor_result.rc == 0
      changed_when: _mor_result.rc == 0

    - name: Generate Image Source manifest
      ansible.builtin.shell: >
        set -o pipefail;
        echo -e "{{ _mor_result.stdout }}" |
        sed -n '/apiVersion/,$p' |
        sed -e 's/name:.*/name: release-{{ mor_version }}/'
      register: is_release

    - name: Write Image Source manifest
      ansible.builtin.copy:
        dest: "{{ mor_cache_dir }}/{{ mor_version }}/imagesource.yaml"
        owner: "{{ mor_owner }}"
        group: "{{ mor_group }}"
        mode: "0644"
        setype: httpd_sys_content_t
        content: "{{ is_release.stdout }}"
      become: true
...
