---
- name: "Check if OpenShift client tools have been unpacked"
  ansible.builtin.stat:
    path: "{{ mor_cache_dir }}/{{ mor_version }}/oc"
    get_checksum: false
  register: unpacked
  when:
    - not mor_force  # we don't care to stat files if we're forcing

- name: "Unarchive client tarball"
  ansible.builtin.unarchive:
    src: "{{ mor_cache_dir }}/{{ mor_version }}/openshift-client-linux-{{ mor_version }}.tar.gz"
    dest: "{{ mor_cache_dir }}/{{ mor_version }}"
    owner: "{{ mor_owner }}"
    group: "{{ mor_group }}"
    mode: "0755"
    remote_src: true
    exclude:
      - README.md
  when:
    - mor_force or not unpacked.stat.exists

- name: Tasks for el8 on 4.16+
  when:
    - ansible_distribution_major_version == '8'
    - mor_version is version("4.16", ">=")
  block:
    - name: Create temporary directory for oc client
      ansible.builtin.tempfile:
        state: directory
        prefix: _mor_tmp_dir.
      register: _mor_tmp_dir

    - name: Download required latest openshift client for el8 in 4.16+
      ansible.builtin.unarchive:
        src: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz"
        dest: "{{ _mor_tmp_dir.path }}"
        remote_src: true
        mode: "0755"
      register: _mor_result
      retries: 3
      delay: 10
      until: _mor_result is not failed

    - name: Extract el8 client for 4.16+
      ansible.builtin.command: >
        {{ _mor_tmp_dir.path }}/oc adm release extract
        --registry-config={{ mor_auths_file }}
        --command=oc.rhel8
        --from {{ mor_pull_url }}
        --to "{{ mor_cache_dir }}/{{ mor_version }}"
      register: _mor_extract_cmd
      until: _mor_extract_cmd is succeeded
      retries: 9
      delay: 10
      changed_when: false

    # redhatci.ocp.installer 4.16+ for el8 expects a rhel8 tarball
    # required only for nightly builds
    # using community.general.archive generates the tarball but
    # throws an exception: load_file_common_arguments() unexpected keyword argument 'path'
    - name: Create a client tarball for el8 on 4.16+
      ansible.builtin.shell: >
        tar czf
        "{{ mor_cache_dir }}/{{ mor_version }}/openshift-client-linux-amd64-rhel8-{{ mor_version }}.tar.gz"
        -C "{{ mor_cache_dir }}/{{ mor_version }}"
        oc
        kubectl
      warn: false
      changed_when: true

    - name: Delete temporary directory for oc client
      ansible.builtin.file:
        path: "{{ _mor_tmp_dir.path }}"
        state: absent

...
