---

- name: Assert the required variables are defined
  ansible.builtin.assert:
    that:
      - gcr_ssh_key_path is defined
      - gcr_ssh_key_path | length > 0
      - gcr_ztp_gitops_repo is defined
      - gcr_ztp_gitops_repo | length > 0

- name: Add Git repository SSH key to argoCD
  community.kubernetes.k8s:
    api_version: v1
    kind: ConfigMap
    name: argocd-ssh-known-hosts-cm
    namespace: openshift-gitops
    resource_definition:
      labels:
        app.kubernetes.io/name: argocd-cm
        app.kubernetes.io/part-of: argocd
      data:
        gcr_ssh_known_hosts: |
          {{ gcr_ssh_known_hosts }}
  when: gcr_ssh_known_hosts is defined
  no_log: true

- name: Register key
  ansible.builtin.set_fact:
    gcr_ssh_key: "{{ lookup('file', gcr_ssh_key_path) }}"
  no_log: true

- name: Create temporary template directory
  ansible.builtin.tempfile:
    state: directory
    suffix: build
  register: temp_dir

- name: Template the private repo resource for Argo
  ansible.builtin.template:
    src: ssh_private_repo.yaml.j2
    dest: "{{ temp_dir.path }}/ssh_private_repo.yaml"
    mode: '0644'

- name: Apply ssh private repo
  community.kubernetes.k8s:
    src: "{{ temp_dir.path }}/ssh_private_repo.yaml"
  no_log: true

- name: Remove temporary directory
  ansible.builtin.file:
    path: "{{ temp_dir.path }}"
    state: absent
