---
- name: Get vbmc node state
  ansible.builtin.shell: |
    set -eo pipefail
    vbmc list | awk '/{{ item }}/ {print $4,$8}'
  register: vbmc_status
  with_items: "{{ vbmc_nodes }}"

- name: Check and run vbmc node if it is down
  ansible.builtin.command: "vbmc start {{ item.item }}"
  with_items: "{{ vbmc_status.results }}"
  when: item.stdout.split()[0]  == 'down'

- name: Create dictionary with vbmc port
  ansible.builtin.set_fact:
      vbmc_ports: "{{ vbmc_ports | default({}) | combine({item.item: item.stdout.split()[1]}) }}"
  with_items: "{{ vbmc_status.results }}"

- name: Include firewalld rules check
  ansible.builtin.include_tasks: firewalld.yml
