- name: Install firewalld
  become: true
  ansible.builtin.package:
    name:
      - firewalld
    state: installed

- name: Set firewall zone to public
  ansible.builtin.set_fact:
    zone: public
  when: ansible_distribution_version|int < 8

- name: Allow access to port vbmc from baremetal network
  ignore_errors: true
  become: true
  ansible.posix.firewalld:
    zone: "{{ zone }}"
    port: "{{ item.value }}/udp"
    permanent: true
    state: enabled
    immediate: true
  with_dict:
    - "{{ vbmc_ports }}"
