---
- name: Install hook
  when: hook_action == 'install'
  become: true
  block:
    - name: Install
      ansible.builtin.include_tasks: install.yml
    - name: Configure
      ansible.builtin.include_tasks: configure.yml
    - name: Register vars for instackenv template
      ansible.builtin.set_fact:
        vbmc_ports: "{{ vbmc_ports }}"
        vbmc_management_address: "{{ vbmc_management_address }}"

- name: Remove/cleanup hook
  become: true
  block:
    - name: Check
      ansible.builtin.include_tasks: check.yml
      when: hook_action == 'check'
    - name: Cleanup
      ansible.builtin.include_tasks: cleanup.yml
      when: hook_action == 'cleanup'
    - name: Remove
      ansible.builtin.include_tasks: remove.yml
      when: hook_action == 'remove'
