---
- name: Check for any vbmc processes
  ansible.builtin.command: pgrep vbmc
  register: vbmc_proc
  failed_when: false
  changed_when: false

- name: Remove existing Virtual BMCs
  ansible.builtin.shell: |
    {{ vbmc_bin }} stop {{ hostvars[vbmc_node].original_name | default(vbmc_node) }}
    {{ vbmc_bin }} delete {{ hostvars[vbmc_node].original_name | default(vbmc_node) }}
  failed_when: false
  when:
    - vbmc_proc.rc == 0
    - vbmc_node is defined
