---
- name: Handle the situation when cert project already exists
  ansible.builtin.include_role:
    name: create_certification_project
    tasks_from: check_if_container_project_exists
  when: check_for_existing_projects | bool

- name: Helm Chart Certification Project
  ansible.builtin.include_role:
    name: create_certification_project
    tasks_from: create_project
  when: helmchart.create_helmchart_project | default(false) | bool

- name: Update the Helm Chart project with company info when cert_settings is defined
  ansible.builtin.include_role:
    name: create_certification_project
    tasks_from: update_project
  when:
    - cert_settings is defined
    - cert_project_id | default('') | length
...
