---
- name: "Get API request counts for a workload ns {{ da_ns }}"
  community.kubernetes.k8s_info:
    kind: APIRequestCount
    namespace: "{{ da_ns }}"
  register: deprecated_api_apirequestcount
  no_log: true

- name: "Extract deprecated and to-be-deprecated API for {{ da_ns }}"
  vars:
    query: "resources[*].{name: metadata.name, removedInRelease: status.removedInRelease}[?removedInRelease != null]"
  ansible.builtin.set_fact:
    da_removed_api: "{{ deprecated_api_apirequestcount | json_query(query) | flatten | unique }}"

- name: "Compute OCP compatibility of the workload API for {{ da_ns }}"
  vars:
    ocp_filename: "{{ deprecated_api_logs.path }}/apirequestcounts_ocp_compatibility_{{ da_ns }}_junit.xml"
  set_fact:
    ocp_compatibility: "{{ da_removed_api | redhatci.ocp.ocp_compatibility(da_ocp_version, ocp_filename) }}"
...
