---
- name: "Configure to use existing disconnected registry"
  delegate_to: localhost
  block:
    - name: "Get stats of {{ disconnected_registry_mirrors_file }}"
      ansible.builtin.stat:
        path: "{{ disconnected_registry_mirrors_file }}"
      register: drm_file

    - name: "Check if mirrors file exists"
      ansible.builtin.fail:
        msg:
          - "The disconnected_registry_mirrors_file is defined, but does not exist"
      when: not drm_file.stat.exists | bool

    - name: "Read the contents of mirrors file"
      ansible.builtin.slurp:
        src: "{{ disconnected_registry_mirrors_file }}"
      register: disconnected_registry_trustbundle
      no_log: true

    - name: "Set the install_config_appends fact"
      ansible.builtin.set_fact:
        install_config_appends: "{{ disconnected_registry_trustbundle.content | string | b64decode }}"
      no_log: true

    - name: "Get stats of auths file"
      ansible.builtin.stat:
        path: "{{ disconnected_registry_auths_file }}"
      register: dra_file

    - name: "Check if disconnected auths file exists"
      ansible.builtin.fail:
        msg:
          - "The disconnected_registry_auths_file is defined, but does not exist"
      when: not dra_file.stat.exists | bool

    - name: "Read disconnected auths"
      ansible.builtin.slurp:
        src: "{{ disconnected_registry_auths_file }}"
      register: disconnected_auths_b64
      no_log: true

    - name: "Append auth to pullsecret"
      ansible.builtin.shell: |
        echo '{{ pullsecret }}' | jq -c \
          '.auths += {{ disconnected_auths_b64.content | string | b64decode }}'
      register: new_pullsecret
      no_log: true

    - name: "Set pullsecret with new auth"
      ansible.builtin.set_fact:
        pullsecret: "  {{ new_pullsecret.stdout }}"
      no_log: true
...
