---
- name: Verify that SSH key for ansible user exists
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/.ssh/id_rsa.pub"
  register: sshkeypath
  tags: installconfig

- name: Get the contents of the ssh key for ansible user
  ansible.builtin.slurp:
    src: "{{ ansible_user_dir }}/.ssh/id_rsa.pub"
  register: sshkey
  when: sshkeypath.stat.exists | bool
  tags: installconfig

- name: Set Fact for the ssh key of ansible user
  ansible.builtin.set_fact:
    key: "{{ sshkey['content'] | b64decode }}"
  tags: installconfig

- name: Generate install-config.yaml
  ansible.builtin.template:
    src: install-config.j2
    dest: "{{ dir }}/install-config.yaml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  when:
    - pullsecret is defined
    - pullsecret | length > 0
  tags: installconfig

- name: Make a backup of the install-config.yaml file
  ansible.builtin.copy:
    src: "{{ dir }}/install-config.yaml"
    dest: "{{ dir }}/install-config.yaml.bkup"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
    remote_src: true
  tags: installconfig
