---
- name: Create OpenShift Manifest
  ansible.builtin.command: |
    {{ ocp_binary_path }}/openshift-install --dir {{ dir }} create manifests
  tags: manifests

- name: Ensure the manifests dir is owned by {{ ansible_user }}
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    recurse: true
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  with_items:
    - "{{ dir }}/openshift"
    - "{{ dir }}/manifests"
  tags: manifests
