---
- name: Check if override path is defined for extra openshift manifests
  ansible.builtin.set_fact:
    extramanifestsopenshift_path: "{{ customize_extramanifestsopenshift_path | default('roles/sno_installer/files/openshift/') }}"

- name: Add Manifests from openshift files dir
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ dir }}/openshift/"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "u=rw,g=r,o=r"
  with_fileglob:
    - "{{ extramanifestsopenshift_path }}/*"
  tags: extramanifests

- name: Check if override path is defined for extramanifests
  ansible.builtin.set_fact:
    extramanifests_path: "{{ customize_extramanifests_path | default('roles/sno_installer/files/manifests/') }}"

- name: Add Manifests from manifest files dir
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ dir }}/manifests/"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "u=rw,g=r,o=r"
  with_fileglob:
    - "{{ extramanifests_path }}/*"
  tags: extramanifests

- name: Manage chrony configuration
  when:
    - clock_servers is defined
    - clock_servers | length > 0
  tags:
    - extramanifests
  block:
    - name: Create chrony.conf
      ansible.builtin.set_fact:
        chronyconfig: "{{ lookup('template', 'chrony.conf.j2') | b64encode }}"

    - name: Inject chrony.conf in a machine-config object
      ansible.builtin.template:
        src: etc-chrony.conf.j2
        dest: "{{ dir }}/openshift/98-{{ item }}-etc-chrony.conf.yaml"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "u=rw,g=r,o=r"
      with_items:
        - master
