---
- name: Get list of all VMs
  community.libvirt.virt:
    command: list_vms
  register: all_vms
  become: true
  tags: cleanup

- name: Get list of all running VMs
  community.libvirt.virt:
    command: list_vms
    state: running
  register: running_vms
  become: true
  tags: cleanup

- name: Get list of all paused VMs
  community.libvirt.virt:
    command: list_vms
    state: paused
  register: paused_vms
  become: true
  tags: cleanup

- name: Destroy old SNO VMs, if any
  community.libvirt.virt:
    name: "{{ item }}"
    command: destroy
  with_items:
    - "{{ running_vms.list_vms }}"
    - "{{ paused_vms.list_vms }}"
  when: item is search(host['name'])
  become: true
  tags: cleanup

- name: "Undefine old SNO VMs, if any"
  ansible.builtin.command:
    cmd: "virsh undefine --nvram {{ item }}"  # community.libvirt.virt undefine doesn't have the ability to specify --nvram
  with_items: "{{ all_vms.list_vms }}"
  when: item is search(host['name'])
  become: true
  tags: cleanup

- name: Delete old SNO VMs Storage
  ansible.builtin.file:
    path: "{{ default_libvirt_pool_dir }}/{{ host['name'] }}.qcow2"
    state: absent
  become: true
  tags: cleanup
...
