---
- name: "Clone opcap repository"  # noqa: latest[git]
  ansible.builtin.git:
    repo: "{{ opcap_repo }}"
    dest: "{{ opcap_dir.path }}/opcap"

- name: "Use Golang container to build opcap"
  # Launching a container to build the GO bin Dir where the repo has been
  # cloned is bound as a volume (with option Z for SELinux compatibility)
  containers.podman.podman_container:
    name: go-builder
    image: "golang:1.19"
    debug: true
    pids_limit: -1
    log_level: "info"
    command: make -C /opcap build OPCAP_VERSION={{ opcap_version }}
    detach: false
    tty: true
    rm: true
    volume:
      - "{{ opcap_dir.path }}/opcap/:/opcap:Z"
  register: opcap_build
  retries: 4
  delay: 10
  until: opcap_build is not failed

- name: "Check opcap bin"
  ansible.builtin.command:
    cmd: >
      ./bin/opcap version
    chdir: "{{ opcap_dir.path }}/opcap"
...
