---
- name: "Copy Junit template report"
  ansible.builtin.copy:
    src: "junit-report.xml"
    dest: "{{ job_logs.path }}/junit-storage-upgrade.xml"
    mode: "0644"

- name: "Run gather-storage-upgrade-RWO script"
  ansible.builtin.script:
    cmd: >
      {{ role_path }}/scripts/storage-tester-RWO.sh {{ job_logs.path }}/junit-storage-upgrade.xml
      | tee {{ job_logs.path }}/gather-storage-upgrade-tester-RWO.log
  register: upgrade_tester_result_rwo
  retries: 5
  delay: 5
  until: upgrade_tester_result_rwo.rc == 0
  delegate_to: localhost

- name: "Run gather-storage-upgrade-ROX script"
  ansible.builtin.script:
    cmd: >
      {{ role_path }}/scripts/storage-tester-ROX.sh {{ job_logs.path }}/junit-storage-upgrade.xml
      | tee {{ job_logs.path }}/gather-storage-upgrade-tester-ROX.log
  register: upgrade_tester_result_rox
  retries: 5
  delay: 5
  until: upgrade_tester_result_rox.rc == 0
  delegate_to: localhost

- name: "Run gather-storage-upgrade-RWX script"
  ansible.builtin.script:
    cmd: >
      {{ role_path }}/scripts/storage-tester-RWX.sh {{ job_logs.path }}/junit-storage-upgrade.xml
      | tee {{ job_logs.path }}/gather-storage-upgrade-tester-RWX.log
  register: upgrade_tester_result_rwx
  retries: 5
  delay: 5
  until: upgrade_tester_result_rwx.rc == 0
  delegate_to: localhost
