---
- name: Validation for UEFI Boot Manager
  ansible.builtin.assert:
    that:
      - ebm_nodes is defined
      - ebm_nodes | length

- name: Delete UEFI boot entries in nodes
  vars:
    _ebm_script: "{{ lookup('file', 'rm-efiboot') | ansible.builtin.b64encode }}"
  ansible.builtin.shell: >
    set -eo pipefail;
    {{ ebm_oc_path }} debug node/{{ node_name }} --
    bash -c "echo {{ _ebm_script }} | base64 -d > /host/tmp/rm-efiboot";
    {{ ebm_oc_path }} debug node/{{ node_name }} -- chroot /host bash -x /tmp/rm-efiboot;
    {{ ebm_oc_path }} debug node/{{ node_name }} -- rm -f /host/tmp/rm-efiboot;
  async: 120
  poll: 0
  register: _ebm_rm
  loop: "{{ ebm_nodes }}"
  loop_control:
    loop_var: node_name
  changed_when: true

- name: Check boot cleanup status
  ansible.builtin.async_status:
    jid: "{{ result.ansible_job_id }}"
  loop: "{{ _ebm_rm.results }}"
  loop_control:
    loop_var: "result"
  register: _ebm_async_results
  until: _ebm_async_results.finished
  retries: 10
  delay: 12
