---
- name: Create the VM Namespace
  community.kubernetes.k8s:
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ kvirt_vm_namespace }}"
        labels:
          security.openshift.io/scc.podSecurityLabelSync: "false"
          pod-security.kubernetes.io/enforce: "baseline"
          pod-security.kubernetes.io/enforce-version: "latest"

- name: Create the VM
  community.kubernetes.k8s:
    definition: "{{ lookup('template', 'templates/vm-template.yml.j2') }}"

- name: Wait for VirtualMachine to be in desired state
  vars:
    kvirt_vm_state: |-
      {%- if kvirt_vm_running %}
      Running{%- else %}
      Stopped{%- endif %}
  community.kubernetes.k8s_info:
    api: "{{ kvirt_vm_api_version }}"
    kind: VirtualMachine
    name: "{{ kvirt_vm_name }}"
    namespace: "{{ kvirt_vm_namespace }}"
  register: kvirt_vm_info
  until:
    - kvirt_vm_info.resources is defined
    - kvirt_vm_info.resources[0].status.printableStatus == kvirt_vm_state
  retries: 60
  delay: 5
...
