---
- name: Run validations
  ansible.builtin.include_tasks: validations.yml

- name: "Create the VM"
  ansible.builtin.include_tasks: create-vm.yml
  loop: "{{ vm_configs }}"
  loop_control:
    loop_var: vm
    label: "{{ vm.name }}"
...
