---
- name: Create clusterconfigs dir
  ansible.builtin.file:
    path: "{{ dir }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  tags: clusterconfigs
