---
- name: Validation
  ansible.builtin.include_tasks: 00_validation.yml
  tags:
    - validation
    - use_registry

- name: Create clusterconfig dirs
  ansible.builtin.include_tasks: 05_create_config_install_dirs.yml
  tags:
    - clusterconfig

- name: Get OCP client
  ansible.builtin.include_tasks: 10_get_oc.yml
  tags:
    - cleanup
    - getoc

- name: Extract installer
  ansible.builtin.include_tasks: 20_extract_installer.yml
  tags:
    - pullsecret
    - extract

- name: Set RHCOS image paths
  ansible.builtin.include_tasks: 23_rhcos_image_paths.yml
  tags:
    - rhcospath

- name: Read SSH key
  ansible.builtin.include_tasks: 25_read_ssh_key.yml
  tags:
    - ssh_key

- name: Execute UPI install hook
  ansible.builtin.include_tasks: '{{ hookdir }}/hooks/upi-install.yml'
  loop: "{{ dci_config_dirs }}"
  loop_control:
    loop_var: hookdir
