---
- name: Get Hosted Cluster info
  community.kubernetes.k8s_info:
    api_version: hypershift.openshift.io/v1beta1
    kind: HostedCluster
    namespace: "{{ ah_clusters_ns }}"
    name: "{{ ah_cluster_generated_name }}"
  register: hosted_cluster

- name: Delete cluster
  ansible.builtin.shell:
    cmd: >
      set -e;
      {{ ah_hcp_cli_path }} destroy cluster {{ ah_cluster_type }}
      --name={{ ah_cluster_generated_name }}
      --namespace={{ ah_clusters_ns }}
      --infra-id={{ ah_cluster_generated_name }}
      --cluster-grace-period 0
  changed_when: false
  when:
    - hosted_cluster.resources | length == 1
...
