---
- name: Set cluster name
  ansible.builtin.set_fact:
    ah_cluster_generated_name: "{{ ah_cluster_name | default(lookup('password', '/dev/null length=10 chars=ascii_lowercase,digits'), true) }}"
  run_once: true

- name: Hypershift validations
  ansible.builtin.include_tasks: validations.yml

- name: Create working directory
  ansible.builtin.tempfile:
    state: directory
  register: ah_tmp_dir

- name: Hypershift cli
  ansible.builtin.include_tasks: download-cli.yml

- name: Delete existent cluster
  ansible.builtin.include_tasks: delete-cluster.yml
  when:
    - ah_force_deploy | bool

- name: Hypershift cluster creation
  ansible.builtin.include_tasks: create-cluster.yml
