---
- name: Delete the Flow collector
  community.kubernetes.k8s:
    api_version: flows.netobserv.io/v1beta1
    kind: FlowCollector
    name: "cluster"
    state: absent
    wait: true

- name: Delete the namespace netobserv
  community.kubernetes.k8s:
    state: absent
    api: "v1"
    kind: "Namespace"
    name: "netobserv"
    wait: true
...
