---
- name: Retrieve branch name
  ansible.builtin.command:
    cmd: >
      git branch --show-current
    chdir: "{{ operator_sdk_source_dir }}"
  register: operator_sdk_branch_name

- name: Set scorecard_branch
  ansible.builtin.set_fact:
    scorecard_branch: "{{ operator_sdk_branch_name.stdout }}"

- name: Copy read-only source folder to set 0755 mode
  ansible.builtin.copy:
    src: "{{ operator_sdk_source_dir }}/"
    dest: "{{ scorecard_tmp_dir.path }}/operator-sdk-source/"
    mode: "0755"

- name: Set operator_sdk_img name
  ansible.builtin.set_fact:
    operator_sdk_img: "{{ scorecard_dci_local_registry }}/operator-framework/operator-sdk:{{ scorecard_branch }}"

- name: Append the job id if defined to simplify cleanup
  ansible.builtin.set_fact:
    operator_sdk_img: "{{ operator_sdk_img + '-' + job_id }}"
  when: job_id is defined

- name: Build Operator-SDK image
  ansible.builtin.shell:
    cmd: >
      podman buildx build
      -t {{ operator_sdk_img }}
      --label quay.expires-after=1d
      --no-cache
      -f ./images/operator-sdk/Dockerfile
      --load . &&
      podman push
      --authfile {{ scorecard_partner_creds }}
      {{ operator_sdk_img }}
    chdir: "{{ scorecard_tmp_dir.path }}/operator-sdk-source/"

- name: Display Operator-SDK version to ensure that the image build went fine
  ansible.builtin.command: podman run --rm {{ operator_sdk_img }} version
...
