---

name: DCI
on:
  merge_group:
jobs:

  dci-job:
    name: "DCI Merge Job"
    runs-on: bos2
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0        #  Fetch all history to be able to look at all the merge commits in dci-merge.sh

      - name: DCI Job
        run: |
          set -ex
          git fetch origin ${{ github.event.merge_group.base_sha }}
          git fetch origin ${{ github.event.merge_group.head_sha }}
          if git diff --name-only ${{ github.event.merge_group.base_sha }} ${{ github.event.merge_group.head_sha }} | grep -E 'roles/|plugins/'; then
            echo "Starting DCI job"
            export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
            ./hack/dci-merge.sh ${{ github.event.merge_group.head_sha }}
          else
            echo "No code change"
          fi

...
