---

name: DCI Merge Queue
on:
  merge_group:
jobs:

  dci-job:
    name: "DCI Merge Job"
    runs-on: bos2
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0        #  Fetch all history to be able to look at the merge commits in dci-merge.sh

      - name: DCI Job
        run: |
          set -ex
          export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          ./hack/dci-merge.sh ${{ github.event.merge_group.base_sha }} ${{ github.event.merge_group.head_sha }}

...
