---

name: DCI
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:

  dci-job:
    name: "Maybe Schedule a DCI Job"
    runs-on: bos2
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Maybe call dci-check-change
        run: |
          set -x
          ./hack/maybe-dci-check-change ${{ github.event.pull_request.html_url }}

...
