---

name: Stale issues/PRs
on:
  schedule:
    - cron: "0 9 * * 1-5"  # Weekdays at 09:00 UTC

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: 'This issue is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 7 days'
          days-before-stale: 30
          days-before-close: 7
          stale-pr-message: 'This PR is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 7 days'
